### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by flomero** [flomero/webserv#1]
Do something similar to [NGINX Config](https://nginx.org/en/docs/beginners_guide.html)

# TODOS
- [x] Support multiple Servers
- [ ] Default Servers (The first server for a host:port will be the default for this host:port)
- [x] Otpions
  - [x] Port
  - [x] Host
  - [x] Server Name
  - [x] Default Error Pages
  - [x] Client Body Size Limit
- [x] Setup routes with rules:
  - [x] list of accepted HTTP methods
  - [x] a HTTP redirection
  - [x] a directory or a file from where the file should be searched
  - [x] Turn on or off directory listing
  - [x] Set a default file to answer if the request is a directory
  - [x] Execute CGI based on certain file extension (for example .php)
  - [x] Make it work with POST and GET methods.
  - [x] Make the route able to accept uploaded files and configure where they should
be saved.

**Comment by GREAULouen** [comment]
Add a <route_option> possibility:
<route_option> ::= "index" <string> ";"

**Comment by GREAULouen** [comment]
Grammar rule verification :

- [ ] listen has host or port or both, never empty
- [ ] index can have multiple file but need at least one
- [ ] Single value rules can't be empty if present (default values set if not present)
- [ ] For associative rules, make sure that there's always both values & they're the right type (error_page, cgi, ...)
- [ ] "return" rule: for 3xx error_code => URL, for any other: nothing or string (TBC)

Configuration data validation required :

- [ ] At least one server
- [ ] IPv4 formatting 
- [ ] Port number
- [ ] index existence
- [ ] error_page existence
- [ ] cgi executable existence
- [ ] cgi extension starts with "." & is not empty after it

Verification after all parsed :

- [ ] Different server_name & host/port pair
- [ ] No duplicate cgi extension in a route
